changes to publish results.

diff --git a/.github/workflows/spineapp_sanity.yaml b/.github/workflows/spineapp_sanity.yaml
--- a/.github/workflows/spineapp_sanity.yaml
+++ b/.github/workflows/spineapp_sanity.yaml
@@ -60,18 +60,24 @@ jobs:
        sudo apt install -y python3-nose libxml2-utils vlc
        cd edge-ai-suites-repo/manufacturing-ai-suite/industrial-edge-insights-vision/tests/robot_files
        robot test.robot 
-       mkdir -p /tmp/test_results
-       cp -r report.html log.html output.xml  /tmp/test_results/
-       passed=$(xmllint --xpath "//return/status[@status='PASS']" ./output.xml | wc -l) || true
-       failed=$(xmllint --xpath "//return/status[@status='FAIL']" ./output.xml | wc -l) || true
-       not_run=$(xmllint --xpath "//return/status[@status='NOT RUN']" ./output.xml | wc -l) || true
-       total=$((passed + failed + not_run))
-       echo "### Sanity Test Summary" >> $GITHUB_STEP_SUMMARY
-       echo "- Total: $total" >> $GITHUB_STEP_SUMMARY
-       echo "- ✅ Passed: $passed" >> $GITHUB_STEP_SUMMARY
-       echo "- ❌ Failed: $failed" >> $GITHUB_STEP_SUMMARY
-       echo "- ⏭️ Not Run: $not_run" >> $GITHUB_STEP_SUMMARY
-       echo "- 📄 [Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
+       
+    - name: Copy and Publish results
+      if: always()
+      run: |
+        mkdir -p /tmp/test_results
+        cd edge-ai-suites-repo/manufacturing-ai-suite/industrial-edge-insights-vision/tests/robot_files
+        cp -r report.html log.html output.xml  /tmp/test_results/
+        passed=$(xmllint --xpath "//return/status[@status='PASS']" ./output.xml | wc -l) || true
+        failed=$(xmllint --xpath "//return/status[@status='FAIL']" ./output.xml | wc -l) || true
+        not_run=$(xmllint --xpath "//return/status[@status='NOT RUN']" ./output.xml | wc -l) || true
+        total=$((passed + failed + not_run))
+        echo "### Sanity Test Summary" >> $GITHUB_STEP_SUMMARY
+        echo "- Total: $total" >> $GITHUB_STEP_SUMMARY
+        echo "- ✅ Passed: $passed" >> $GITHUB_STEP_SUMMARY
+        echo "- ❌ Failed: $failed" >> $GITHUB_STEP_SUMMARY
+        echo "- ⏭️ Not Run: $not_run" >> $GITHUB_STEP_SUMMARY
+        echo "- 📄 [Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
+    
     - name: Upload Scan artifact to Github
       uses: actions/upload-artifact@v4
       if: always()
